# Generated by Django 4.1.2 on 2022-10-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('p_hip', models.PositiveIntegerField(default=0)),
                ('p_waist', models.PositiveIntegerField(default=0)),
                ('minimum_pressure', models.PositiveIntegerField(default=0)),
                ('maximum_pressure', models.PositiveIntegerField(default=0)),
                ('imc', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Condicion Fisica',
                'verbose_name_plural': 'Condiciones Fisicas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='users')),
                ('surname', models.CharField(max_length=50)),
                ('objective_weight', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('s', 'Saludable'), ('r', 'Regular'), ('i', 'Insaludable')], max_length=1)),
                ('condition', models.ManyToManyField(to='users.usercondition')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': ('Usuario',),
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
