# Generated by Django 4.1.2 on 2022-10-30 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercondition',
            old_name='p_hip',
            new_name='hip',
        ),
        migrations.RenameField(
            model_name='usercondition',
            old_name='p_waist',
            new_name='waist',
        ),
        migrations.AlterField(
            model_name='usercondition',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 30)),
        ),
    ]
