# Generated by Django 4.1.2 on 2022-10-30 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_p_hip_usercondition_hip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercondition',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 30, 1, 33, 41, 546462, tzinfo=datetime.timezone.utc)),
        ),
    ]
