# Generated by Django 4.1.2 on 2022-11-04 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usercondition_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercondition',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 4, 4, 6, 30, 558466, tzinfo=datetime.timezone.utc)),
        ),
    ]
