# Generated by Django 4.1.2 on 2022-11-07 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_status_date_alter_status_hip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 7, 1, 41, 9, 179273, tzinfo=datetime.timezone.utc)),
        ),
    ]
